# src/services/routers_generator.py
"""
RoutersGenerator — تولید routers/*.py (CRUD endpoints) از روی Schema
─────────────────────────────────
قدم ۵.۳

برای هر جدول یه فایل توی app/routers/ می‌سازه با ۶ endpoint:
  • GET    /{table}            → لیست (skip/limit/search)
  • GET    /{table}/count      → شمارش
  • GET    /{table}/{id}       → یه آیتم
  • POST   /{table}            → ساخت
  • PATCH  /{table}/{id}       → ویرایش
  • DELETE /{table}/{id}       → حذف

نکات:
  • جدول‌های Junction (user_roles, role_permissions) → بدون PATCH
  • password/token توی create → hash می‌شن (فقط password)
  • search توی فیلدهای searchable با ilike
"""

from typing import List, Optional
from src.models.custom_schema import Project, CustomTable, CustomColumn


# ═══════════════════════════════════════════════════════════
# فیلدهای حساس (hash پسورد توی create)
# ═══════════════════════════════════════════════════════════
PASSWORD_FIELDS = {"password"}   # فقط این‌ها hash می‌شن

JUNCTION_TABLES = {"user_roles", "role_permissions"}


class RoutersGenerator:
    """تولیدکننده‌ی routers/*.py"""

    def __init__(self, project: Project, tables: List[CustomTable]):
        self.project = project
        self.tables = tables
        self._table_by_name = {t.name: t for t in tables}

    # ═══════════════════════════════════════════════════════
    # نام کلاس (هم‌راستا با python_generator و schemas_generator)
    # ═══════════════════════════════════════════════════════
    @staticmethod
    def _class_name(table_name: str) -> str:
        SPECIAL = {
            "users":           "User",
            "roles":           "Role",
            "permissions":     "Permission",
            "sessions":        "Session",
            "user_profiles":   "UserProfile",
            "user_roles":      "UserRole",
            "role_permissions":"RolePermission",
            "password_resets": "PasswordReset",
            "otp_codes":       "OtpCode",
            "login_attempts":  "LoginAttempt",
            "user_activities": "UserActivity",
            "jwt_blacklist":   "JwtBlacklist",
        }
        if table_name in SPECIAL:
            return SPECIAL[table_name]
        return "".join(part.capitalize() for part in table_name.split("_"))

    # ═══════════════════════════════════════════════════════
    # ابزار: ستون‌های searchable
    # ═══════════════════════════════════════════════════════
    @staticmethod
    def _searchable_columns(table: CustomTable) -> List[CustomColumn]:
        """ستون‌هایی که is_searchable=True و نوعشون رشته‌ست"""
        result = []
        for col in table.columns:
            if not col.is_searchable:
                continue
            if col.is_primary:
                continue
            dtype = col.data_type.upper().strip()
            if dtype.startswith("VARCHAR") or dtype in ("TEXT", "LONGTEXT"):
                result.append(col)
        return result

    # ═══════════════════════════════════════════════════════
    # ابزار: تولید بلاک search
    # ═══════════════════════════════════════════════════════
    def _render_search_block(self, table: CustomTable, cls: str) -> str:
        searchable = self._searchable_columns(table)
        if not searchable:
            return ""

        lines = ["    if search:"]
        conditions = [f"{cls}.{c.name}.ilike(f\"%{{search}}%\")" for c in searchable]
        joined = " |\n            ".join(conditions)
        lines.append(f"        stmt = stmt.where(")
        lines.append(f"            {joined}")
        lines.append(f"        )")
        return "\n".join(lines)

    # ═══════════════════════════════════════════════════════
    # ابزار: تولید بلاک hash password توی create
    # ═══════════════════════════════════════════════════════
    @staticmethod
    def _has_password(table: CustomTable) -> bool:
        for col in table.columns:
            if col.name in PASSWORD_FIELDS:
                return True
        return False

    # ═══════════════════════════════════════════════════════
    # تولید یک router
    # ═══════════════════════════════════════════════════════
    def generate_router(self, table: CustomTable) -> str:
        cls = self._class_name(table.name)
        table_name = table.name
        is_junction = table_name in JUNCTION_TABLES

        # ─── header ───
        header = f'''# app/routers/{table_name}.py
"""
{cls} — CRUD endpoints
Auto-generated by Py App Maker
"""

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import func, select
from sqlalchemy.orm import Session as DBSession

from app.database import get_db
from app.models.models import {cls}
from app.schemas.schemas import {cls}Create, {cls}Update, {cls}Response
'''

        # ─── اگه password داره، import hash ───
        if self._has_password(table):
            header += "from app.auth.password import hash_password\n"

        header += f'''

router = APIRouter(prefix="/{table_name}", tags=["{table_name}"])
'''

        parts = [header]

        # ═══════════════════════════════════════════════════
        # 1. GET /count
        # ═══════════════════════════════════════════════════
        parts.append(f'''

@router.get("/count", response_model=dict)
def count_{table_name}(db: DBSession = Depends(get_db)):
    """شمارش کل {table.fa_name or table_name}"""
    total = db.scalar(select(func.count()).select_from({cls}))
    return {{"count": total}}
''')

        # ═══════════════════════════════════════════════════
        # 2. GET / (list)
        # ═══════════════════════════════════════════════════
        search_block = self._render_search_block(table, cls)
        search_param = ""
        if self._searchable_columns(table):
            search_param = '''
    search: Optional[str] = Query(None, description="جستجو در فیلدهای searchable"),'''

        list_body = f'''
@router.get("", response_model=List[{cls}Response])
def list_{table_name}(
    skip: int = Query(0, ge=0),
    limit: int = Query(50, ge=1, le=500),{search_param}
    db: DBSession = Depends(get_db),
):
    """لیست {table.fa_name or table_name} با pagination"""
    stmt = select({cls})
'''

        if search_block:
            list_body += f"{search_block}\n"

        list_body += f'''    stmt = stmt.offset(skip).limit(limit)
    return db.scalars(stmt).all()
'''
        parts.append(list_body)

        # ═══════════════════════════════════════════════════
        # 3. GET /{item_id}
        # ═══════════════════════════════════════════════════
        parts.append(f'''

@router.get("/{{item_id}}", response_model={cls}Response)
def get_{table_name}(item_id: int, db: DBSession = Depends(get_db)):
    """دریافت یک {table.fa_name or table_name}"""
    obj = db.get({cls}, item_id)
    if not obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="{cls} not found",
        )
    return obj
''')

        # ═══════════════════════════════════════════════════
        # 4. POST /
        # ═══════════════════════════════════════════════════
        create_body = f'''

@router.post("", response_model={cls}Response, status_code=status.HTTP_201_CREATED)
def create_{table_name}(payload: {cls}Create, db: DBSession = Depends(get_db)):
    """ساخت {table.fa_name or table_name} جدید"""
    data = payload.model_dump()
'''
        if self._has_password(table):
            create_body += '''    # ─── hash password ───
    if data.get("password"):
        data["password"] = hash_password(data["password"])
'''

        create_body += f'''    obj = {cls}(**data)
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj
'''
        parts.append(create_body)

        # ═══════════════════════════════════════════════════
        # 5. PATCH /{item_id}  (skip اگه junction)
        # ═══════════════════════════════════════════════════
        if not is_junction:
            update_body = f'''

@router.patch("/{{item_id}}", response_model={cls}Response)
def update_{table_name}(
    item_id: int,
    payload: {cls}Update,
    db: DBSession = Depends(get_db),
):
    """ویرایش جزئی {table.fa_name or table_name}"""
    obj = db.get({cls}, item_id)
    if not obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="{cls} not found",
        )
    data = payload.model_dump(exclude_unset=True)
'''
            if self._has_password(table):
                update_body += '''    # ─── hash password اگه تغییر کرده ───
    if data.get("password"):
        data["password"] = hash_password(data["password"])
'''

            update_body += f'''    for key, value in data.items():
        setattr(obj, key, value)
    db.commit()
    db.refresh(obj)
    return obj
'''
            parts.append(update_body)

        # ═══════════════════════════════════════════════════
        # 6. DELETE /{item_id}
        # ═══════════════════════════════════════════════════
        parts.append(f'''

@router.delete("/{{item_id}}", status_code=status.HTTP_204_NO_CONTENT)
def delete_{table_name}(item_id: int, db: DBSession = Depends(get_db)):
    """حذف {table.fa_name or table_name}"""
    obj = db.get({cls}, item_id)
    if not obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="{cls} not found",
        )
    db.delete(obj)
    db.commit()
    return None
''')

        return "".join(parts)

    # ═══════════════════════════════════════════════════════
    # تولید همه‌ی routerها
    # ═══════════════════════════════════════════════════════
    def generate_all(self) -> dict:
        """
        برمی‌گردونه: { "users": "...", "roles": "...", ... }
        کلیدها نام فایل (بدون .py) هستن.
        """
        result = {}
        for table in self.tables:
            result[table.name] = self.generate_router(table)
        return result